{
 "title": "Prometheus Mailgun Exporter",
 "description": "Mailgun Stats using Prometheus Mailgun Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "domain", "query": "mailgun_domain_stats_accepted" },
   { "name": "accepted_type", "query": "mailgun_domain_stats_accepted" },
   {
    "name": "failed_permanent_type",
    "query": "mailgun_domain_stats_failed_permanent"
   },
   {
    "name": "failed_temporaryt_type",
    "query": "mailgun_domain_stats_failed_temporary"
   },
   { "name": "delivered_type", "query": "mailgun_domain_stats_delivered" }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "graph",
   "description": "Is the domain active (1) or disabled (0)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_state{name=~\"$domain\"}",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(mailgun_domain_state{name=~\"$domain\"}[$__range])",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Complaints",
   "type": "graph",
   "description": "Complaints within the metrics time window.\n\nThe email recipient clicked on the spam complaint button within their email client.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_stats_complained{name=~\"$domain\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Complaints :: Total :: Percentage",
   "type": "gauge",
   "description": "The email recipient clicked on the spam complaint button within their email client.\n\nAnything >= 0.05% is bad and can cause the domain to be disabled",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(mailgun_domain_stats_complained{name=~\"$domain\"} / ignoring (type) group_right mailgun_domain_stats_delivered{name=~\"$domain\",type=~\"$delivered_type\"}) * 100 >= 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failed :: Permanent",
   "type": "graph",
   "description": "Permanently failed emails within the metrics time window.\n\nMailgun could not deliver the email to the recipient email server (bounce).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_stats_failed_permanent{name=~\"$domain\",type=~\"$failed_permanent_type\"}",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Failed :: Permanent :: Total :: Percentage",
   "type": "gauge",
   "description": "Mailgun could not deliver the email to the recipient email server. This could be due to being suppressed or bad email address (bounce)\n\nAnything >= 5% is bad and can cause the domain to be disabled",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(mailgun_domain_stats_failed_permanent{name=~\"$domain\",type=~\"$failed_permanent_type\"} / ignoring (type) group_left mailgun_domain_stats_accepted{name=~\"$domain\",type=~\"outgoing\"}) * 100 >= 0",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "graph",
   "description": "Accepted emails within the metrics time window\n\nMailgun accepted the request to send/forward the email and the message has been placed in queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_stats_accepted{name=~\"$domain\",type=~\"$accepted_type\"}",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Delivered",
   "type": "graph",
   "description": "Delivered emails within the metrics time window\n\nMailgun sent the email and it was accepted by the recipient email server.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_stats_delivered{name=~\"$domain\",type=~\"$delivered_type\"}",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Delivered :: Total :: Percentage",
   "type": "gauge",
   "description": "Percentage of emails delivered based on how much Mailgun accepted.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "(mailgun_domain_stats_delivered{name=~\"$domain\",type=~\"$delivered_type\"} / ignoring (type) group_left mailgun_domain_stats_accepted{name=~\"$domain\",type=\"outgoing\"}) * 100",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Failed :: Temporary",
   "type": "graph",
   "description": "Temporarily failed emails within the metrics time window.\n\nMailgun could not deliver the email to the recipient email server (bounce).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_stats_failed_temporary{name=~\"$domain\",type=~\"$failed_temporaryt_type\"}",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Failed :: Temporary :: Total :: Percentage",
   "type": "gauge",
   "description": "Mailgun could not deliver the email to the recipient email server.\n\nAnything >= 5% is bad and can cause the domain to be disabled",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "(mailgun_domain_stats_failed_temporary{name=~\"$domain\",type=~\"$failed_temporaryt_type\"} / ignoring (type) group_left mailgun_domain_stats_accepted{name=~\"$domain\",type=~\"outgoing\"}) * 100 >= 0",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "Unsubscribed",
   "type": "graph",
   "description": "Unsubscribes within the metrics time window\n\nThe email recipient clicked on the unsubscribe link. Unsubscribe tracking must be enabled in the Mailgun control panel.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mailgun_domain_stats_unsubscribed{name=~\"$domain\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unsubscribed :: Total :: Percentage",
   "type": "gauge",
   "description": "The email recipient clicked on the unsubscribe link. Unsubscribe tracking must be enabled in the Mailgun control panel.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "(mailgun_domain_stats_unsubscribed{name=~\"$domain\"} / ignoring (type) group_right mailgun_domain_stats_delivered{name=~\"$domain\",type=~\"$delivered_type\"}) * 100 >= 0",
     "legendFormat": "{{name}} :: {{ type }}"
    }
   ]
  },
  {
   "title": "API State",
   "type": "graph",
   "description": "Is the Mailgun API up (1) or down (0)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mailgun_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "API Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(mailgun_up[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}