// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mailgun/mailgun-go/v5/mtypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailgunClient creates a new instance of MockMailgunClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailgunClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailgunClient {
	mock := &MockMailgunClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailgunClient is an autogenerated mock type for the MailgunClient type
type MockMailgunClient struct {
	mock.Mock
}

type MockMailgunClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailgunClient) EXPECT() *MockMailgunClient_Expecter {
	return &MockMailgunClient_Expecter{mock: &_m.Mock}
}

// GetDomains provides a mock function for the type MockMailgunClient
func (_mock *MockMailgunClient) GetDomains(ctx context.Context) ([]mtypes.Domain, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDomains")
	}

	var r0 []mtypes.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]mtypes.Domain, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []mtypes.Domain); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mtypes.Domain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMailgunClient_GetDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomains'
type MockMailgunClient_GetDomains_Call struct {
	*mock.Call
}

// GetDomains is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMailgunClient_Expecter) GetDomains(ctx interface{}) *MockMailgunClient_GetDomains_Call {
	return &MockMailgunClient_GetDomains_Call{Call: _e.mock.On("GetDomains", ctx)}
}

func (_c *MockMailgunClient_GetDomains_Call) Run(run func(ctx context.Context)) *MockMailgunClient_GetDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMailgunClient_GetDomains_Call) Return(domains []mtypes.Domain, err error) *MockMailgunClient_GetDomains_Call {
	_c.Call.Return(domains, err)
	return _c
}

func (_c *MockMailgunClient_GetDomains_Call) RunAndReturn(run func(ctx context.Context) ([]mtypes.Domain, error)) *MockMailgunClient_GetDomains_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function for the type MockMailgunClient
func (_mock *MockMailgunClient) GetMetrics(ctx context.Context, domain string) (*mtypes.Metrics, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 *mtypes.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*mtypes.Metrics, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *mtypes.Metrics); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mtypes.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMailgunClient_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockMailgunClient_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockMailgunClient_Expecter) GetMetrics(ctx interface{}, domain interface{}) *MockMailgunClient_GetMetrics_Call {
	return &MockMailgunClient_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx, domain)}
}

func (_c *MockMailgunClient_GetMetrics_Call) Run(run func(ctx context.Context, domain string)) *MockMailgunClient_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMailgunClient_GetMetrics_Call) Return(metrics *mtypes.Metrics, err error) *MockMailgunClient_GetMetrics_Call {
	_c.Call.Return(metrics, err)
	return _c
}

func (_c *MockMailgunClient_GetMetrics_Call) RunAndReturn(run func(ctx context.Context, domain string) (*mtypes.Metrics, error)) *MockMailgunClient_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}
